// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: security_scan.proto

package security_scanpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecurityScanService_ScanForVulnerabilities_FullMethodName = "/securityscanpb.SecurityScanService/ScanForVulnerabilities"
)

// SecurityScanServiceClient is the client API for SecurityScanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// --- Security Scan Service ---
// Performs SAST, secret detection, and configuration vulnerability analysis
type SecurityScanServiceClient interface {
	// Perform static analysis, secret detection, and config scanning
	ScanForVulnerabilities(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
}

type securityScanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecurityScanServiceClient(cc grpc.ClientConnInterface) SecurityScanServiceClient {
	return &securityScanServiceClient{cc}
}

func (c *securityScanServiceClient) ScanForVulnerabilities(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, SecurityScanService_ScanForVulnerabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecurityScanServiceServer is the server API for SecurityScanService service.
// All implementations must embed UnimplementedSecurityScanServiceServer
// for forward compatibility.
//
// --- Security Scan Service ---
// Performs SAST, secret detection, and configuration vulnerability analysis
type SecurityScanServiceServer interface {
	// Perform static analysis, secret detection, and config scanning
	ScanForVulnerabilities(context.Context, *ScanRequest) (*ScanResponse, error)
	mustEmbedUnimplementedSecurityScanServiceServer()
}

// UnimplementedSecurityScanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecurityScanServiceServer struct{}

func (UnimplementedSecurityScanServiceServer) ScanForVulnerabilities(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanForVulnerabilities not implemented")
}
func (UnimplementedSecurityScanServiceServer) mustEmbedUnimplementedSecurityScanServiceServer() {}
func (UnimplementedSecurityScanServiceServer) testEmbeddedByValue()                             {}

// UnsafeSecurityScanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecurityScanServiceServer will
// result in compilation errors.
type UnsafeSecurityScanServiceServer interface {
	mustEmbedUnimplementedSecurityScanServiceServer()
}

func RegisterSecurityScanServiceServer(s grpc.ServiceRegistrar, srv SecurityScanServiceServer) {
	// If the following call pancis, it indicates UnimplementedSecurityScanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecurityScanService_ServiceDesc, srv)
}

func _SecurityScanService_ScanForVulnerabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityScanServiceServer).ScanForVulnerabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityScanService_ScanForVulnerabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityScanServiceServer).ScanForVulnerabilities(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecurityScanService_ServiceDesc is the grpc.ServiceDesc for SecurityScanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecurityScanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "securityscanpb.SecurityScanService",
	HandlerType: (*SecurityScanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScanForVulnerabilities",
			Handler:    _SecurityScanService_ScanForVulnerabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "security_scan.proto",
}
