// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: security_scan.proto

package security_scanpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcePath    string                 `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_security_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_security_scan_proto_rawDescGZIP(), []int{0}
}

func (x *ScanRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        string                 `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`                            // Full JSON report generated by scanner
	TotalFinds    int32                  `protobuf:"varint,2,opt,name=total_finds,json=totalFinds,proto3" json:"total_finds,omitempty"` // Total number of issues found
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_security_scan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_scan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_security_scan_proto_rawDescGZIP(), []int{1}
}

func (x *ScanResponse) GetReport() string {
	if x != nil {
		return x.Report
	}
	return ""
}

func (x *ScanResponse) GetTotalFinds() int32 {
	if x != nil {
		return x.TotalFinds
	}
	return 0
}

var File_security_scan_proto protoreflect.FileDescriptor

const file_security_scan_proto_rawDesc = "" +
	"\n" +
	"\x13security_scan.proto\x12\x0esecurityscanpb\".\n" +
	"\vScanRequest\x12\x1f\n" +
	"\vsource_path\x18\x01 \x01(\tR\n" +
	"sourcePath\"G\n" +
	"\fScanResponse\x12\x16\n" +
	"\x06report\x18\x01 \x01(\tR\x06report\x12\x1f\n" +
	"\vtotal_finds\x18\x02 \x01(\x05R\n" +
	"totalFinds2j\n" +
	"\x13SecurityScanService\x12S\n" +
	"\x16ScanForVulnerabilities\x12\x1b.securityscanpb.ScanRequest\x1a\x1c.securityscanpb.ScanResponseB7Z5github.com/unarya/unarya/lib/proto/pb/security_scanpbb\x06proto3"

var (
	file_security_scan_proto_rawDescOnce sync.Once
	file_security_scan_proto_rawDescData []byte
)

func file_security_scan_proto_rawDescGZIP() []byte {
	file_security_scan_proto_rawDescOnce.Do(func() {
		file_security_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_security_scan_proto_rawDesc), len(file_security_scan_proto_rawDesc)))
	})
	return file_security_scan_proto_rawDescData
}

var file_security_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_security_scan_proto_goTypes = []any{
	(*ScanRequest)(nil),  // 0: securityscanpb.ScanRequest
	(*ScanResponse)(nil), // 1: securityscanpb.ScanResponse
}
var file_security_scan_proto_depIdxs = []int32{
	0, // 0: securityscanpb.SecurityScanService.ScanForVulnerabilities:input_type -> securityscanpb.ScanRequest
	1, // 1: securityscanpb.SecurityScanService.ScanForVulnerabilities:output_type -> securityscanpb.ScanResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_security_scan_proto_init() }
func file_security_scan_proto_init() {
	if File_security_scan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_security_scan_proto_rawDesc), len(file_security_scan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_security_scan_proto_goTypes,
		DependencyIndexes: file_security_scan_proto_depIdxs,
		MessageInfos:      file_security_scan_proto_msgTypes,
	}.Build()
	File_security_scan_proto = out.File
	file_security_scan_proto_goTypes = nil
	file_security_scan_proto_depIdxs = nil
}
