// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: parser.proto

package parserpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcePath    string                 `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_parser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_parser_proto_rawDescGZIP(), []int{0}
}

func (x *ParseRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

type ParseResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Language       string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`                                // Detected primary language
	Dependencies   []string               `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty"`                        // List of dependency files and data
	CodeStructure  string                 `protobuf:"bytes,3,opt,name=code_structure,json=codeStructure,proto3" json:"code_structure,omitempty"` // Tree-like or JSON structure
	Representation string                 `protobuf:"bytes,4,opt,name=representation,proto3" json:"representation,omitempty"`                    // e.g., "json", "tree"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_parser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_parser_proto_rawDescGZIP(), []int{1}
}

func (x *ParseResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ParseResponse) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *ParseResponse) GetCodeStructure() string {
	if x != nil {
		return x.CodeStructure
	}
	return ""
}

func (x *ParseResponse) GetRepresentation() string {
	if x != nil {
		return x.Representation
	}
	return ""
}

var File_parser_proto protoreflect.FileDescriptor

const file_parser_proto_rawDesc = "" +
	"\n" +
	"\fparser.proto\x12\bparserpb\"/\n" +
	"\fParseRequest\x12\x1f\n" +
	"\vsource_path\x18\x01 \x01(\tR\n" +
	"sourcePath\"\x9e\x01\n" +
	"\rParseResponse\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\"\n" +
	"\fdependencies\x18\x02 \x03(\tR\fdependencies\x12%\n" +
	"\x0ecode_structure\x18\x03 \x01(\tR\rcodeStructure\x12&\n" +
	"\x0erepresentation\x18\x04 \x01(\tR\x0erepresentation2M\n" +
	"\rParserService\x12<\n" +
	"\tParseCode\x12\x16.parserpb.ParseRequest\x1a\x17.parserpb.ParseResponseB0Z.github.com/unarya/unarya/lib/proto/pb/parserpbb\x06proto3"

var (
	file_parser_proto_rawDescOnce sync.Once
	file_parser_proto_rawDescData []byte
)

func file_parser_proto_rawDescGZIP() []byte {
	file_parser_proto_rawDescOnce.Do(func() {
		file_parser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parser_proto_rawDesc), len(file_parser_proto_rawDesc)))
	})
	return file_parser_proto_rawDescData
}

var file_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_parser_proto_goTypes = []any{
	(*ParseRequest)(nil),  // 0: parserpb.ParseRequest
	(*ParseResponse)(nil), // 1: parserpb.ParseResponse
}
var file_parser_proto_depIdxs = []int32{
	0, // 0: parserpb.ParserService.ParseCode:input_type -> parserpb.ParseRequest
	1, // 1: parserpb.ParserService.ParseCode:output_type -> parserpb.ParseResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_parser_proto_init() }
func file_parser_proto_init() {
	if File_parser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parser_proto_rawDesc), len(file_parser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parser_proto_goTypes,
		DependencyIndexes: file_parser_proto_depIdxs,
		MessageInfos:      file_parser_proto_msgTypes,
	}.Build()
	File_parser_proto = out.File
	file_parser_proto_goTypes = nil
	file_parser_proto_depIdxs = nil
}
