// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: ai.proto

package aipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         []byte                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"` // Serialized tensor or model input
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"` // Optional model name or version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *PredictRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"` // Serialized tensor or model output
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *PredictResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

type PredictBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inputs        [][]byte               `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"` // Multiple serialized inputs
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictBatchRequest) Reset() {
	*x = PredictBatchRequest{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictBatchRequest) ProtoMessage() {}

func (x *PredictBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictBatchRequest.ProtoReflect.Descriptor instead.
func (*PredictBatchRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *PredictBatchRequest) GetInputs() [][]byte {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *PredictBatchRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type PredictBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       [][]byte               `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"` // Multiple serialized outputs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictBatchResponse) Reset() {
	*x = PredictBatchResponse{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictBatchResponse) ProtoMessage() {}

func (x *PredictBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictBatchResponse.ProtoReflect.Descriptor instead.
func (*PredictBatchResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

func (x *PredictBatchResponse) GetOutputs() [][]byte {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type ReloadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelPath     string                 `protobuf:"bytes,1,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"` // Path or object store URI to model file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadModelRequest) Reset() {
	*x = ReloadModelRequest{}
	mi := &file_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadModelRequest) ProtoMessage() {}

func (x *ReloadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadModelRequest.ProtoReflect.Descriptor instead.
func (*ReloadModelRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{4}
}

func (x *ReloadModelRequest) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

type ReloadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadModelResponse) Reset() {
	*x = ReloadModelResponse{}
	mi := &file_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadModelResponse) ProtoMessage() {}

func (x *ReloadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadModelResponse.ProtoReflect.Descriptor instead.
func (*ReloadModelResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{5}
}

func (x *ReloadModelResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ReloadModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{6}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // e.g. "loaded", "error", "no_model"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{7}
}

func (x *StatusResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type AIAnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`                                // Programming language (e.g. "Python", "Go")
	CodeStructure string                 `protobuf:"bytes,2,opt,name=code_structure,json=codeStructure,proto3" json:"code_structure,omitempty"` // Code structure, AST, or intermediate representation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIAnalyzeRequest) Reset() {
	*x = AIAnalyzeRequest{}
	mi := &file_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIAnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIAnalyzeRequest) ProtoMessage() {}

func (x *AIAnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIAnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AIAnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{8}
}

func (x *AIAnalyzeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AIAnalyzeRequest) GetCodeStructure() string {
	if x != nil {
		return x.CodeStructure
	}
	return ""
}

type AIAnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Insights      string                 `protobuf:"bytes,1,opt,name=insights,proto3" json:"insights,omitempty"`     // Example: "Detected MVC pattern", "Possible logic flaw"
	Confidence    string                 `protobuf:"bytes,2,opt,name=confidence,proto3" json:"confidence,omitempty"` // Confidence level or score
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIAnalyzeResponse) Reset() {
	*x = AIAnalyzeResponse{}
	mi := &file_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIAnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIAnalyzeResponse) ProtoMessage() {}

func (x *AIAnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIAnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AIAnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{9}
}

func (x *AIAnalyzeResponse) GetInsights() string {
	if x != nil {
		return x.Insights
	}
	return ""
}

func (x *AIAnalyzeResponse) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\apb.aipb\"<\n" +
	"\x0ePredictRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\fR\x05input\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\")\n" +
	"\x0fPredictResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\"C\n" +
	"\x13PredictBatchRequest\x12\x16\n" +
	"\x06inputs\x18\x01 \x03(\fR\x06inputs\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"0\n" +
	"\x14PredictBatchResponse\x12\x18\n" +
	"\aoutputs\x18\x01 \x03(\fR\aoutputs\"3\n" +
	"\x12ReloadModelRequest\x12\x1d\n" +
	"\n" +
	"model_path\x18\x01 \x01(\tR\tmodelPath\"?\n" +
	"\x13ReloadModelResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rStatusRequest\"V\n" +
	"\x0eStatusResponse\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\"U\n" +
	"\x10AIAnalyzeRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12%\n" +
	"\x0ecode_structure\x18\x02 \x01(\tR\rcodeStructure\"O\n" +
	"\x11AIAnalyzeResponse\x12\x1a\n" +
	"\binsights\x18\x01 \x01(\tR\binsights\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\tR\n" +
	"confidence2\xa5\x02\n" +
	"\vAIInference\x12>\n" +
	"\aPredict\x12\x17.pb.aipb.PredictRequest\x1a\x18.pb.aipb.PredictResponse\"\x00\x12M\n" +
	"\fPredictBatch\x12\x1c.pb.aipb.PredictBatchRequest\x1a\x1d.pb.aipb.PredictBatchResponse\"\x00\x12J\n" +
	"\vReloadModel\x12\x1b.pb.aipb.ReloadModelRequest\x1a\x1c.pb.aipb.ReloadModelResponse\"\x00\x12;\n" +
	"\x06Status\x12\x16.pb.aipb.StatusRequest\x1a\x17.pb.aipb.StatusResponse\"\x002Q\n" +
	"\tAIService\x12D\n" +
	"\vAnalyzeCode\x12\x19.pb.aipb.AIAnalyzeRequest\x1a\x1a.pb.aipb.AIAnalyzeResponseB,Z*github.com/unarya/unarya/lib/proto/pb/aipbb\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ai_proto_goTypes = []any{
	(*PredictRequest)(nil),       // 0: pb.aipb.PredictRequest
	(*PredictResponse)(nil),      // 1: pb.aipb.PredictResponse
	(*PredictBatchRequest)(nil),  // 2: pb.aipb.PredictBatchRequest
	(*PredictBatchResponse)(nil), // 3: pb.aipb.PredictBatchResponse
	(*ReloadModelRequest)(nil),   // 4: pb.aipb.ReloadModelRequest
	(*ReloadModelResponse)(nil),  // 5: pb.aipb.ReloadModelResponse
	(*StatusRequest)(nil),        // 6: pb.aipb.StatusRequest
	(*StatusResponse)(nil),       // 7: pb.aipb.StatusResponse
	(*AIAnalyzeRequest)(nil),     // 8: pb.aipb.AIAnalyzeRequest
	(*AIAnalyzeResponse)(nil),    // 9: pb.aipb.AIAnalyzeResponse
}
var file_ai_proto_depIdxs = []int32{
	0, // 0: pb.aipb.AIInference.Predict:input_type -> pb.aipb.PredictRequest
	2, // 1: pb.aipb.AIInference.PredictBatch:input_type -> pb.aipb.PredictBatchRequest
	4, // 2: pb.aipb.AIInference.ReloadModel:input_type -> pb.aipb.ReloadModelRequest
	6, // 3: pb.aipb.AIInference.Status:input_type -> pb.aipb.StatusRequest
	8, // 4: pb.aipb.AIService.AnalyzeCode:input_type -> pb.aipb.AIAnalyzeRequest
	1, // 5: pb.aipb.AIInference.Predict:output_type -> pb.aipb.PredictResponse
	3, // 6: pb.aipb.AIInference.PredictBatch:output_type -> pb.aipb.PredictBatchResponse
	5, // 7: pb.aipb.AIInference.ReloadModel:output_type -> pb.aipb.ReloadModelResponse
	7, // 8: pb.aipb.AIInference.Status:output_type -> pb.aipb.StatusResponse
	9, // 9: pb.aipb.AIService.AnalyzeCode:output_type -> pb.aipb.AIAnalyzeResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
