[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "unarya-ai"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    # list dependencies
]

[tool.setuptools.packages.find]
where = ["src"]