# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\x12\x07pb.aipb\".\n\x0ePredictRequest\x12\r\n\x05input\x18\x01 \x01(\x0c\x12\r\n\x05model\x18\x02 \x01(\t\"!\n\x0fPredictResponse\x12\x0e\n\x06output\x18\x01 \x01(\x0c\"4\n\x13PredictBatchRequest\x12\x0e\n\x06inputs\x18\x01 \x03(\x0c\x12\r\n\x05model\x18\x02 \x01(\t\"<\n\x10\x41IAnalyzeRequest\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x16\n\x0e\x63ode_structure\x18\x02 \x01(\t\"9\n\x11\x41IAnalyzeResponse\x12\x10\n\x08insights\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\t\"\'\n\x14PredictBatchResponse\x12\x0f\n\x07outputs\x18\x01 \x03(\x0c\"(\n\x12ReloadModelRequest\x12\x12\n\nmodel_path\x18\x01 \x01(\t\"2\n\x13ReloadModelResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0f\n\rStatusRequest\"?\n\x0eStatusResponse\x12\r\n\x05model\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t2\xa5\x02\n\x0b\x41IInference\x12>\n\x07Predict\x12\x17.pb.aipb.PredictRequest\x1a\x18.pb.aipb.PredictResponse\"\x00\x12M\n\x0cPredictBatch\x12\x1c.pb.aipb.PredictBatchRequest\x1a\x1d.pb.aipb.PredictBatchResponse\"\x00\x12J\n\x0bReloadModel\x12\x1b.pb.aipb.ReloadModelRequest\x1a\x1c.pb.aipb.ReloadModelResponse\"\x00\x12;\n\x06Status\x12\x16.pb.aipb.StatusRequest\x1a\x17.pb.aipb.StatusResponse\"\x00\x32Q\n\tAIService\x12\x44\n\x0b\x41nalyzeCode\x12\x19.pb.aipb.AIAnalyzeRequest\x1a\x1a.pb.aipb.AIAnalyzeResponseB,Z*github.com/unarya/unarya/lib/proto/pb/aipbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/unarya/unarya/lib/proto/pb/aipb'
  _globals['_PREDICTREQUEST']._serialized_start=21
  _globals['_PREDICTREQUEST']._serialized_end=67
  _globals['_PREDICTRESPONSE']._serialized_start=69
  _globals['_PREDICTRESPONSE']._serialized_end=102
  _globals['_PREDICTBATCHREQUEST']._serialized_start=104
  _globals['_PREDICTBATCHREQUEST']._serialized_end=156
  _globals['_AIANALYZEREQUEST']._serialized_start=158
  _globals['_AIANALYZEREQUEST']._serialized_end=218
  _globals['_AIANALYZERESPONSE']._serialized_start=220
  _globals['_AIANALYZERESPONSE']._serialized_end=277
  _globals['_PREDICTBATCHRESPONSE']._serialized_start=279
  _globals['_PREDICTBATCHRESPONSE']._serialized_end=318
  _globals['_RELOADMODELREQUEST']._serialized_start=320
  _globals['_RELOADMODELREQUEST']._serialized_end=360
  _globals['_RELOADMODELRESPONSE']._serialized_start=362
  _globals['_RELOADMODELRESPONSE']._serialized_end=412
  _globals['_STATUSREQUEST']._serialized_start=414
  _globals['_STATUSREQUEST']._serialized_end=429
  _globals['_STATUSRESPONSE']._serialized_start=431
  _globals['_STATUSRESPONSE']._serialized_end=494
  _globals['_AIINFERENCE']._serialized_start=497
  _globals['_AIINFERENCE']._serialized_end=790
  _globals['_AISERVICE']._serialized_start=792
  _globals['_AISERVICE']._serialized_end=873
# @@protoc_insertion_point(module_scope)
