# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import collector_pb2 as collector__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in collector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CollectorServiceStub(object):
    """--- Collector Service ---
    Responsible for fetching, cloning, and validating source code repositories
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CollectFromGit = channel.unary_unary(
                '/collectorpb.CollectorService/CollectFromGit',
                request_serializer=collector__pb2.GitRequest.SerializeToString,
                response_deserializer=collector__pb2.CollectorResponse.FromString,
                _registered_method=True)
        self.CollectFromArchive = channel.unary_unary(
                '/collectorpb.CollectorService/CollectFromArchive',
                request_serializer=collector__pb2.ArchiveRequest.SerializeToString,
                response_deserializer=collector__pb2.CollectorResponse.FromString,
                _registered_method=True)
        self.CollectFromURL = channel.unary_unary(
                '/collectorpb.CollectorService/CollectFromURL',
                request_serializer=collector__pb2.URLRequest.SerializeToString,
                response_deserializer=collector__pb2.CollectorResponse.FromString,
                _registered_method=True)
        self.ValidateSource = channel.unary_unary(
                '/collectorpb.CollectorService/ValidateSource',
                request_serializer=collector__pb2.ValidateRequest.SerializeToString,
                response_deserializer=collector__pb2.ValidateResponse.FromString,
                _registered_method=True)


class CollectorServiceServicer(object):
    """--- Collector Service ---
    Responsible for fetching, cloning, and validating source code repositories
    """

    def CollectFromGit(self, request, context):
        """Clone repository from Git (GitHub, GitLab, Bitbucket)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectFromArchive(self, request, context):
        """Download and extract ZIP/TAR archives
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectFromURL(self, request, context):
        """Download files from HTTP/HTTPS
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSource(self, request, context):
        """Validate incoming source URL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CollectFromGit': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectFromGit,
                    request_deserializer=collector__pb2.GitRequest.FromString,
                    response_serializer=collector__pb2.CollectorResponse.SerializeToString,
            ),
            'CollectFromArchive': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectFromArchive,
                    request_deserializer=collector__pb2.ArchiveRequest.FromString,
                    response_serializer=collector__pb2.CollectorResponse.SerializeToString,
            ),
            'CollectFromURL': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectFromURL,
                    request_deserializer=collector__pb2.URLRequest.FromString,
                    response_serializer=collector__pb2.CollectorResponse.SerializeToString,
            ),
            'ValidateSource': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSource,
                    request_deserializer=collector__pb2.ValidateRequest.FromString,
                    response_serializer=collector__pb2.ValidateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'collectorpb.CollectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('collectorpb.CollectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CollectorService(object):
    """--- Collector Service ---
    Responsible for fetching, cloning, and validating source code repositories
    """

    @staticmethod
    def CollectFromGit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collectorpb.CollectorService/CollectFromGit',
            collector__pb2.GitRequest.SerializeToString,
            collector__pb2.CollectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectFromArchive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collectorpb.CollectorService/CollectFromArchive',
            collector__pb2.ArchiveRequest.SerializeToString,
            collector__pb2.CollectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectFromURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collectorpb.CollectorService/CollectFromURL',
            collector__pb2.URLRequest.SerializeToString,
            collector__pb2.CollectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collectorpb.CollectorService/ValidateSource',
            collector__pb2.ValidateRequest.SerializeToString,
            collector__pb2.ValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
