# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestrator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12orchestrator.proto\x12\x0eorchestratorpb\")\n\x0fPipelineRequest\x12\x16\n\x0erepository_url\x18\x01 \x01(\t\"3\n\x10PipelineResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t2i\n\x13OrchestratorService\x12R\n\rStartPipeline\x12\x1f.orchestratorpb.PipelineRequest\x1a .orchestratorpb.PipelineResponseB6Z4github.com/unarya/unarya/lib/proto/pb/orchestratorpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/unarya/unarya/lib/proto/pb/orchestratorpb'
  _globals['_PIPELINEREQUEST']._serialized_start=38
  _globals['_PIPELINEREQUEST']._serialized_end=79
  _globals['_PIPELINERESPONSE']._serialized_start=81
  _globals['_PIPELINERESPONSE']._serialized_end=132
  _globals['_ORCHESTRATORSERVICE']._serialized_start=134
  _globals['_ORCHESTRATORSERVICE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
