# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: parser.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'parser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cparser.proto\x12\x08parserpb\"#\n\x0cParseRequest\x12\x13\n\x0bsource_path\x18\x01 \x01(\t\"g\n\rParseResponse\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x65pendencies\x18\x02 \x03(\t\x12\x16\n\x0e\x63ode_structure\x18\x03 \x01(\t\x12\x16\n\x0erepresentation\x18\x04 \x01(\t2M\n\rParserService\x12<\n\tParseCode\x12\x16.parserpb.ParseRequest\x1a\x17.parserpb.ParseResponseB0Z.github.com/unarya/unarya/lib/proto/pb/parserpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'parser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/unarya/unarya/lib/proto/pb/parserpb'
  _globals['_PARSEREQUEST']._serialized_start=26
  _globals['_PARSEREQUEST']._serialized_end=61
  _globals['_PARSERESPONSE']._serialized_start=63
  _globals['_PARSERESPONSE']._serialized_end=166
  _globals['_PARSERSERVICE']._serialized_start=168
  _globals['_PARSERSERVICE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
