# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import parser_pb2 as parser__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in parser_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ParserServiceStub(object):
    """--- Parser Service ---
    Responsible for code parsing, AST generation, and dependency extraction
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseCode = channel.unary_unary(
                '/parserpb.ParserService/ParseCode',
                request_serializer=parser__pb2.ParseRequest.SerializeToString,
                response_deserializer=parser__pb2.ParseResponse.FromString,
                _registered_method=True)


class ParserServiceServicer(object):
    """--- Parser Service ---
    Responsible for code parsing, AST generation, and dependency extraction
    """

    def ParseCode(self, request, context):
        """Parse a given source directory and produce structured metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseCode': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseCode,
                    request_deserializer=parser__pb2.ParseRequest.FromString,
                    response_serializer=parser__pb2.ParseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'parserpb.ParserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('parserpb.ParserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ParserService(object):
    """--- Parser Service ---
    Responsible for code parsing, AST generation, and dependency extraction
    """

    @staticmethod
    def ParseCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parserpb.ParserService/ParseCode',
            parser__pb2.ParseRequest.SerializeToString,
            parser__pb2.ParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
