# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import security_scan_pb2 as security__scan__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in security_scan_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SecurityScanServiceStub(object):
    """--- Security Scan Service ---
    Performs SAST, secret detection, and configuration vulnerability analysis
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScanForVulnerabilities = channel.unary_unary(
                '/securityscanpb.SecurityScanService/ScanForVulnerabilities',
                request_serializer=security__scan__pb2.ScanRequest.SerializeToString,
                response_deserializer=security__scan__pb2.ScanResponse.FromString,
                _registered_method=True)


class SecurityScanServiceServicer(object):
    """--- Security Scan Service ---
    Performs SAST, secret detection, and configuration vulnerability analysis
    """

    def ScanForVulnerabilities(self, request, context):
        """Perform static analysis, secret detection, and config scanning
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecurityScanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScanForVulnerabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanForVulnerabilities,
                    request_deserializer=security__scan__pb2.ScanRequest.FromString,
                    response_serializer=security__scan__pb2.ScanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'securityscanpb.SecurityScanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('securityscanpb.SecurityScanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SecurityScanService(object):
    """--- Security Scan Service ---
    Performs SAST, secret detection, and configuration vulnerability analysis
    """

    @staticmethod
    def ScanForVulnerabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/securityscanpb.SecurityScanService/ScanForVulnerabilities',
            security__scan__pb2.ScanRequest.SerializeToString,
            security__scan__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
