# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: security_scan.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'security_scan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13security_scan.proto\x12\x0esecurityscanpb\"\"\n\x0bScanRequest\x12\x13\n\x0bsource_path\x18\x01 \x01(\t\"3\n\x0cScanResponse\x12\x0e\n\x06report\x18\x01 \x01(\t\x12\x13\n\x0btotal_finds\x18\x02 \x01(\x05\x32j\n\x13SecurityScanService\x12S\n\x16ScanForVulnerabilities\x12\x1b.securityscanpb.ScanRequest\x1a\x1c.securityscanpb.ScanResponseB7Z5github.com/unarya/unarya/lib/proto/pb/security_scanpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'security_scan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/unarya/unarya/lib/proto/pb/security_scanpb'
  _globals['_SCANREQUEST']._serialized_start=39
  _globals['_SCANREQUEST']._serialized_end=73
  _globals['_SCANRESPONSE']._serialized_start=75
  _globals['_SCANRESPONSE']._serialized_end=126
  _globals['_SECURITYSCANSERVICE']._serialized_start=128
  _globals['_SECURITYSCANSERVICE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
