services:
  db:
    image: ${APP_NAME}-postgres:${VERSION}
    container_name: ${APP_NAME}-postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    image: ${APP_NAME}-${FRAMEWORK}:${VERSION}
    container_name: ${APP_NAME}-${FRAMEWORK}
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./:/app
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db
      - redis
    networks:
      - backend

  redis:
    image: ${APP_NAME}-redis:${VERSION}
    container_name: ${APP_NAME}-redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6371:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  db_data:
    name: ${APP_NAME}-postgres-data
  redis_data:
    name: ${APP_NAME}-redis-data

networks:
  backend:
    name: ${APP_NAME}-network
    driver: bridge

# Bake (Buildx) integration
x-bake:
  db:
    dockerfile: Dockerfile.postgres
    tags:
      - ${APP_NAME}-postgres:${VERSION}
    platforms: ["linux/amd64"]
    cache-from: type=registry,ref=${APP_NAME}-postgres:cache
    cache-to: type=registry,ref=${APP_NAME}-postgres:cache,mode=max

  app:
    dockerfile: Dockerfile
    tags:
      - ${APP_NAME}-${FRAMEWORK}:${VERSION}
    platforms: ["linux/amd64"]
    cache-from: type=registry,ref=${APP_NAME}-${FRAMEWORK}:cache
    cache-to: type=registry,ref=${APP_NAME}-${FRAMEWORK}:cache,mode=max

  redis:
    dockerfile: Dockerfile.redis
    tags:
      - ${APP_NAME}-redis:${VERSION}
    platforms: ["linux/amd64"]
    cache-from: type=registry,ref=${APP_NAME}-redis:cache
    cache-to: type=registry,ref=${APP_NAME}-redis:cache,mode=max